apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden.fullname" . }}-icons
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: icons
spec:
  replicas: {{ .Values.icons.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bitwarden.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: icons
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bitwarden.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: icons
    spec:
      containers:
      - name: icons
        image: "{{ .Values.icons.image.repository }}:{{ .Values.icons.image.tag }}"
        imagePullPolicy: {{ .Values.icons.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        resources:
{{ toYaml .Values.icons.resources | indent 10 }}
      tolerations:
{{ toYaml .Values.icons.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.icons.affinity | indent 8 }}
